name: Publish to PyPI

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build-and-publish:
    name: Build and publish release artifacts
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install build tooling
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[dev]"

      - name: Run linters and type checks
        run: |
          black --check .
          isort --check-only .
          flake8 .
          mypy .

      - name: Run tests (fakeredis)
        run: |
          pytest tests/unit/ tests/integration/

      - name: Build distribution
        run: python -m build

      - name: Publish to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: python -m twine upload dist/*
